resource_group_name = "prod_resource_group"
resource_group_location = "westus"
environment = "production"
cis_topic_connstr = "Endpoint=sb://pdus-functions-messaging.servicebus.windows.net/;SharedAccessKeyName=MedlineRelay;SharedAccessKey=eik2gPuWYCMCjx4L9Tc3ytB2xFDBKPzzkp60CFhyF1w=;"
cis_topic = "cis-ms-topic-prod"
cis_subscription = "cis-sub-prod"